name: Build SDK

on:
  pull_request:
    branches:
      - "[0-9]+"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - runs-on: [self-hosted, linux, jammy, x64, xlarge]
          - runs-on: [self-hosted, linux, jammy, ARM64, xlarge]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v6

      - name: Install sdkcraft
        run: sudo snap install sdkcraft --edge --classic

      - name: Pack SDK
        run: sdkcraft pack
