name: Renovate check
on:
  pull_request:
    paths:
      - ".github/workflows/renovate-check.yml"
      - "renovate.json"

  # Allows triggering the workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      enable_ssh_access:
        type: boolean
        description: "Enable ssh access"
        required: false
        default: false

jobs:
  renovate:
    uses: canonical/sdkcraft-actions/.github/workflows/renovate-check.yml@main
    with:
      enable_ssh_access: ${{ inputs.enable_ssh_access || false }}
